name = "prove"
defaultTargets = ["DigitStream", "GraphLang"]

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "DigitStream"

[[lean_lib]]
name = "GraphLang"

[[lean_lib]]
name = "DigitLaurel"


[[lean_exe]]
name = "main"
root = "Main"
